### ISSUE TITLE
Objective constructors have bad initial keyword args

### ISSUE THREAD

**Issue by aarontrowbridge** [aarontrowbridge/QuantumCollocation.jl#63] opened 2023-12-05 21:17 UTC
**Describe the bug**
Default values for objective constructors used in loading saved objectives have bad values.

**Example**
at line 469 in objectives.jl 

```
function QuadraticSmoothnessRegularizer(;
	name::Symbol=nothing,
    times::AbstractVector{Int}=1:traj.T,
	R::AbstractVector{<:Real}=ones(traj.dims[name]),
	eval_hessian=true
)
```

**Comment by andgoldschmidt** [comment] 2024-05-06 20:44
closing because duplicate of #68

**Closed by andgoldschmidt** 2024-05-06 20:44 UTC
